CREATE SCHEMA IF NOT EXISTS API;

CREATE TABLE ${SCHEMA_NAME}.MODELO_NEGOCIO
(
    PK_MDL_NGC     BIGSERIAL     NOT NULL,
    COD            VARCHAR(256)  NOT NULL,
    DSC 		   VARCHAR(256)  NOT NULL,
    FK_PESSOA      INT8          NOT NULL,
    STA			   CHAR(14)	     NOT NULL,
    DTH_CRIACAO	   TIMESTAMP     NOT NULL,
    DTH_ALTERACAO  TIMESTAMP	 NULL,
    DTH_INATIVACAO TIMESTAMP	 NULL,
    PRIMARY KEY (PK_MDL_NGC)
);
ALTER TABLE ${SCHEMA_NAME}.MODELO_NEGOCIO
    ADD CONSTRAINT FK_MDL_NGC_PESSOA_ID FOREIGN KEY (FK_PESSOA) REFERENCES ${SCHEMA_NAME}.PESSOA;


﻿INSERT INTO ${SCHEMA_NAME}.MODELO_NEGOCIO (PK_MDL_NGC, COD, DSC, FK_PESSOA, STA, DTH_CRIACAO, DTH_ALTERACAO, DTH_INATIVACAO) 
                                   VALUES (23, 'MDL-001', 'Informatica', 1, 'ATIVO', '2024-01-19T09:45:30', null, null );
﻿INSERT INTO ${SCHEMA_NAME}.MODELO_NEGOCIO (PK_MDL_NGC, COD, DSC, FK_PESSOA, STA, DTH_CRIACAO, DTH_ALTERACAO, DTH_INATIVACAO) 
                                   VALUES (25, 'MDL-002', 'Varejo', 1, 'INATIVO', '2024-01-19T09:48:30', null, null );
