CREATE SCHEMA IF NOT EXISTS API;

CREATE TABLE ${SCHEMA_NAME}.PESSOA
(
    ID              BIGSERIAL    NOT NULL,
    CPF             VARCHAR(11)  NOT NULL,
    DATA_NASCIMENTO DATE         NOT NULL,
    NOME            VARCHAR(200) NOT NULL,
    SEXO            CHAR(1)      NOT NULL,
    PRIMARY KEY (ID)
);

﻿INSERT INTO ${SCHEMA_NAME}.PESSOA (ID, DATA_NASCIMENTO, NOME, CPF, SEXO) VALUES (1, '1985-02-22', 'TONY STARK', '98030795068', 'M');
INSERT INTO ${SCHEMA_NAME}.PESSOA (ID, DATA_NASCIMENTO, NOME, CPF, SEXO) VALUES (2, '1945-01-30', 'STEVE ROGERS', '33314654022', 'M');
