CREATE SCHEMA IF NOT EXISTS API;

CREATE TABLE ${SCHEMA_NAME}.MODELO_NEGOCIO
(
    PK_MDL_NGC     BIGSERIAL     NOT NULL,
    COD            TIMESTAMP     NOT NULL,
    DSC 		   CHAR(1)       NOT NULL,
    FK_PESSOA      INT8          NOT NULL,
    PRIMARY KEY (PK_MDL_NGC)
);
ALTER TABLE ${SCHEMA_NAME}.MODELO_NEGOCIO
    ADD CONSTRAINT FK_MDL_NGC_PESSOA_ID FOREIGN KEY (FK_PESSOA) REFERENCES ${SCHEMA_NAME}.PESSOA;

